### ISSUE TITLE
Healthcheck fails for MariaDB container

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#245]
When attempting to use a docker-compose file derived from the `docker-compose-mysql.yml` file, the MariaDB is indefinitely stuck on the healthcheck (and eventually stopped)

https://github.com/Clinical-Genomics/chanjo2/blob/54ce6104a6323df9702ae837860fc340d285ee66/docker-compose-mysql.yml#L15

Checking inside it, it seems `mysql` isn't present, which is used for the health check.

Updating it to `mariadb` I got it up and running:

`test: "mariadb --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\"" `

**Comment by northwestwitch** [comment]
Ok, thanks for the feedback, I'll look into it!

**Comment by northwestwitch** [comment]
Hi again, I wrote [a fix](#247) to this issue, would you like to review? Thanks! :)
