### ISSUE TITLE
Trouble getting /report calls to the correct end point, round 2

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#292]
Hi, sorry, I am back with another finding-the-`/report`-endpoint issue. It is yet again due to us running multiple software at sub paths in one domain (starting to think that we should look over how we do this ... but anyways, we are not there yet).

I _think_ it is a different problem from last round (https://github.com/Clinical-Genomics/scout/issues/4539) but please let me know if I have already been told the solution without fully internalizing it..

This time my issue is that we are using subroutes in NGINX for the different Scout services, while Chanjo2 is written expecting to be at the "base" path.

I.e. our Chanjo2 is residing at **scoutdomain.se/chanjo2**. When navigating to it from Scout, you end up at **scoutdomain.se/chanjo2/report**.

So far so good. But when updating thresholds and regenerating the report, the POST requests goes to **scoutdomain.se/report**. I.e. it does not remember the subpath. This yields a 404 error.

Below is how it currently looks (in version 1.6) when trying it out in production. Trying out the same payload in the example below but to `cmdscout2.lund.skane.se/chanjo2/report` and it works.

<img width="359" alt="chanjo2_not_found" src="https://github.com/Clinical-Genomics/chanjo2/assets/7374399/87419095-a16e-4230-b352-bdd9cf20365b">

I looked around a bit, and I got the impression that this isn't easily solved by NGINX configuration (I might be wrong). Would it be possible for Chanjo2 to be aware of its "base path"?

**Comment by northwestwitch** [comment]
Ah I see. The easiest solution would be running the app via uvicorn and provide a root path ([docs]( https://fastapi.tiangolo.com/advanced/behind-a-proxy/#providing-the-root_path)). but the app is launched in docker using gunicorn..
Question, do you run the app in docker-compose? Because you could try something like this perhaps -> https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/55#issuecomment-1279601836

If it doesn't work we could attempt [this](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/55#issuecomment-879903517), but perhaps give a try to the solution above first

**Comment by Jakob37** [comment]
> Ah I see. The easiest solution would be running the app via uvicorn and provide a root path ([docs](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#providing-the-root_path)). but the app is launched in docker using gunicorn.. Question, do you run the app in docker-compose? Because you could try something like this perhaps -> [tiangolo/uvicorn-gunicorn-fastapi-docker#55 (comment)](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/55#issuecomment-1279601836)
> 
> If it doesn't work we could attempt [this](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/55#issuecomment-879903517), but perhaps give a try to the solution above first

OK interesting! I'll give it a go. Yes, I am running it in docker-compose. I'll try that solution!

**Comment by Jakob37** [comment]
OK, tested now. Took some time for me to realize that `uvicorn` already is installed in the Chanjo2-container. But in the end, simply running it as such works nicely:

```
command: ["uvicorn", "chanjo2.main:app", "--host=0.0.0.0", "--port=8000", "--workers=2", "--log-level=info", "--root-path=/chanjo2"]
```

Thanks! Have a nice 1st May!

**Comment by northwestwitch** [comment]
> OK, tested now. Took some time for me to realize that `uvicorn` already is installed in the Chanjo2-container. But in the end, simply running it as such works nicely:
> 
> ```
> command: ["uvicorn", "chanjo2.main:app", "--host=0.0.0.0", "--port=8000", "--workers=2", "--log-level=info", "--root-path=/chanjo2"]
> ```
> 
> Thanks! Have a nice 1st May!

Great! You too! 😊
