### ISSUE TITLE
Modify report endpoints to only accept forms and not json data?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/chanjo2#293]
Perhaps maintenance and usage would be easier. Right now if you go to swagger you don't see the params that you could pass to the endpoints any more..

**Comment by northwestwitch** [comment]
While coverage endpoint can accept json

**Comment by seallard** [comment]
The endpoints should only accept json and return json, it is the standard format used for data in web API:s. Consuming the Chanjo API would be a lot easier if all of the endpoints accepted and returned valid json.

**Comment by northwestwitch** [comment]
> The endpoints should accept json and return json, it is the standard format used for data in web API:s. Consuming the Chanjo API would be a lot easier if all of the endpoints accepted and returned valid json.

That's how I had it in the beginning. But then after integrating with scout we (me and people in Lund) realised that to be able to integrate well and to be able to modify reports on the fly from the HTML page of the report then it has to accept a form. See also:
https://github.com/Clinical-Genomics/scout/issues/4539

**Comment by northwestwitch** [comment]
But of course one can have 2 endpoints, one that accepts form data and one that accepts json!

**Comment by seallard** [comment]
It would be nice to support both formats then! Usually the client sending the request specifies in the header which data format it wants (for example `Accept: application/json` or `Accept: application/xml`)

**Comment by seallard** [comment]
That would be a single endpoint still. However, the response would be formatted based on the provided header.

**Comment by northwestwitch** [comment]
> That would be a single endpoint still. However, the response would be formatted based on the provided header.

Yeah I know, that's why I opened this issue. Currently we don't have any use to an endpoint that accepts json, so I was thinking to only accept form data. Hadn't have time to work on this yet
