### ISSUE TITLE
Occasionally large differences in coverage for same gene region in same sample

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#299]
I stumbled on this when looking at some real samples, where some had an average coverage of >800x (where 30-50 is expected).

I drilled down into the individual genes using `d4tools`, and found that some genes had a huge claimed coverage. Later ones had a coverage around 30-50. This seems to be what pulls up the mean coverage. 

```
$ d4 stat --region intervals.bed <sample>_coverage.d4 | sort -k4,4 -n -r
19      49635292        49640143        30268.71325499897
10      119651380       119677819       12509.91527667461
11      19182030        19210571        6439.562664237413
3       14125015        14143680        3130.0193410125903
...
```

Looking manually in IGV it looked more like 30-40x coverage.

Running only that specific region, I get more reasonable coverage. But this is really strange isn't it? That we get hugely different coverage for the same region dependent on when running one or several regions.

```
$ d4 stat --region gene_19.bed <sample>_coverage.d4
19      49635292        49640143        39.8051948051948
```

Numbers from running d4tools manually seems to check out with what Chanjo2 is displaying, so no fault on Chanjo2's part here what I can see.

I followed up by checking whether I can reproduce this in Chanjo2. It seems I can.

Here is the target gene by itself:

![chanjo2_single_gene](https://github.com/Clinical-Genomics/chanjo2/assets/7374399/450ffd5b-faa9-46fc-bad4-3660a7e0e1d0)

Here is a second gene by itself:

![chanjo2_second_gene](https://github.com/Clinical-Genomics/chanjo2/assets/7374399/126249f3-1277-452e-9418-ea33a208e04e)

Here is the coverage when running these two together, note how the coverage jumps to ~15000, which checks out with that one gene suddenly jumps to 30000x coverage.

![chanjo2_two_genes](https://github.com/Clinical-Genomics/chanjo2/assets/7374399/22be8086-15ae-498d-9488-92f92647d734)

I plan to investigate this a bit more and raise the issue to the d4tools devs later today. Maybe it could be resolved by generating the d4-files with different settings (now I have non-indexed default settings). But does anyway seem quite concerning if this is a real issue.

If I have missed something, please point it out!

**Comment by northwestwitch** [comment]
> Running only that specific region, I get more reasonable coverage. But this is really strange isn't it? That we get hugely different coverage for the same region dependent on when running one or several regions.

I agree, it's weird, A bug perhaps? Tag me on the d4tools issue, so I can also follow!

**Comment by Jakob37** [comment]
It seems like a bug, and it seems to be caused by some intervals sometimes "bleeding" into the subsequent one when supplying many intervals at once (more details in https://github.com/38/d4-format/issues/78). 

I get the same error pattern when trying it on GIAB, so it seems to be more related with which regions are used than the exact content of the d4 file.

All at once (notice that one region diffs)

```
$ d4 stat --region bed/intervals_only_19.bed hg002_coverage.d4
19      4090321 4124122 47.764267329368955
19      45769709        45782552        45.254146227516934
19      49635292        49640143        34655.42465471037
19      55151767        55157773        37.25041625041625
```

One and one

```
$ for interval in bed/intervals_only_19/*.bed; do d4 stat --region ${interval} hg002_coverage.d4; done
19      4090321 4124122 47.764267329368955
19      45769709        45782552        45.254146227516934
19      49635292        49640143        46.97567511853226
19      55151767        55157773        37.25041625041625
```

Content of `bed/intervals_only_19.bed`

```
$ cat bed/intervals_only_19.bed
19      45769709        45782552
19      4090321 4124122
19      49635292        49640143
19      55151767        55157773
```

I wonder why it hasn't been encountered before 🤔 

A temporary non-ideal workaround might be to process the ranges one and one. Not sure how much this would slow down things though. Hope the d4 devs will look into it soon.

**Comment by northwestwitch** [comment]
Well spotted!

**Comment by northwestwitch** [comment]
> A temporary non-ideal workaround for Chanjo2 might be to process the ranges one and one. Not sure how much this would slow down things though. Hope the d4 devs will look into it soon.

It would slow down things quite a bit I think, so that would not be ideal. Let's hope in a quick fix on d4tools. otherwise we'll see

**Comment by northwestwitch** [comment]
I think I'll patch a fix to this issue here on this repo. Then we can always revert the code when they fix it on d4tools. By checking at the other issues and open PRs in that repo it doesn't seem they are maintaining it activelly .. 😞

**Comment by Jakob37** [comment]
Looks like things are moving over at the d4tools 🎉 My fix is merged now. And I saw in another PR that brentp said he was planning to make a new d4tools release soon.

https://github.com/38/d4-format/pull/79

But meanwhile, and with a new hardware setup, we have been discussing whether Chanjo2 actually is an improvement over Chanjo1. If we have the computational resources to generate the Chanjo1-coverage, then the user has a no-wait access to coverage, while using the d4-file, as the coverage is calculated on the fly, it is in principle shifted to the user. 

We haven't fully decided, but we wonder whether actually sticking a bit longer with Chanjo1 is the better choice. How do you guys in Stockholm think about this?

**Comment by northwestwitch** [comment]
That's great to hear, well done! 🚀 
We can patch this repo with their new software when they create a new release!

In our facility, we are moving from Chanjo to Chanjo2. The major **disadvantage of Chanjo is that, although it computes statistics quickly, it only works on a static set of transcripts** and does not consider the sequencing technology (WES, WGS, WTS, etc.). In contrast, Chanjo2 computes statistics on transcripts, exons, or entire genes based on the type of data provided.
Another **advantage of Chanjo2 is that case-specific statistics do not need to be stored in the database**. While the Chanjo database is not complicated, it requires maintenance and a routine to load these statistics into Chanjo immediately before loading the sample into Scout.

I agree with you that the waiting time when producing Chanjo2 reports is a significant drawback. However, most of this time is taken by the function that calculates [coverage completeness (Python code and partly d4tools)](https://github.com/Clinical-Genomics/chanjo2/blob/main/src/chanjo2/meta/handle_completeness_tasks.py), not by the function that computes coverage (which is done by d4tools). I plan to replace this code in the near future with a Rust script that will significantly reduce the waiting time, as Rust is much faster than Python. The problem is that I do not know Rust yet, but I have started studying it. Any chance you might have time and want to contribute to this part?

**Comment by Jakob37** [comment]
> That's great to hear, well done! 🚀 We can patch this repo with their new software when they create a new release!
> 
> In our facility, we are moving from Chanjo to Chanjo2. The major **disadvantage of Chanjo is that, although it computes statistics quickly, it only works on a static set of transcripts** and does not consider the sequencing technology (WES, WGS, WTS, etc.). In contrast, Chanjo2 computes statistics on transcripts, exons, or entire genes based on the type of data provided. Another **advantage of Chanjo2 is that case-specific statistics do not need to be stored in the database**. While the Chanjo database is not complicated, it requires maintenance and a routine to load these statistics into Chanjo immediately before loading the sample into Scout.
> 
> I agree with you that the waiting time when producing Chanjo2 reports is a significant drawback. However, most of this time is taken by the function that calculates [coverage completeness (Python code and partly d4tools)](https://github.com/Clinical-Genomics/chanjo2/blob/main/src/chanjo2/meta/handle_completeness_tasks.py), not by the function that computes coverage (which is done by d4tools). I plan to replace this code in the near future with a Rust script that will significantly reduce the waiting time, as Rust is much faster than Python. The problem is that I do not know Rust yet, but I have started studying it. Any chance you might have time and want to contribute to this part?

OK, thank you very much for this feedback! 

I understand, it sounds like Chanjo2 is the Chanjo-future then. The question for us to discuss is perhaps then whether we should restart Chanjo1 for now until you guys are getting started with Chanjo2, or whether we can complete the jump now.

Our primary concerns right now have been:

(1) Slowness of calculating coverage, putting stone on burden on our geneticists 
(2) The apparent instability of d4-tools

Significantly speeding up the calculations would shift this.. And hopefully now the d4-tools are stable enough, at least for our purposes. Comforting to see some movement in that repo now, with brentp activating.

My prior Rust experience is limited to a single round of Advent of Code, so don't overestimate me there 😅 But as it looks like a focused script, it should probably be doable, and a nice learning.

I'll bring this up for discussion again here locally. I'll be back.

**Comment by Jakob37** [comment]
Would it be possible to put together a new release using the new version 3.10 of d4-tools? Then we would have something that we could use locally.

https://github.com/38/d4-format/releases/tag/v0.3.10

We still haven't had time discuss the Chanjo2-timeline. Will raise it on the next raredisease-meeting later this week.

**Comment by northwestwitch** [comment]
Oh I didn't know that there was a new release of d4tools (repo releases on GitHub are still at version 0.3.8). Sure, I'll work on it. Thursday is my last working day before the summer holidays - then I'll be off for 3 weeks, so I have to wrap up some things before then, but this is an easy one! :)

**Comment by Jakob37** [comment]
> Oh I didn't know that there was a new release of d4tools (repo releases on GitHub are still at version 0.3.8). Sure, I'll work on it. Thursday is my last working day before the summer holidays - then I'll be off for 3 weeks, so I have to wrap up some things before then, but this is an easy one! :)

Thanks! 🙏 

Yes, I saw they had a brief conversation about it in the other PR they merged (https://github.com/38/d4-format/pull/77). Looks like they concluded that a tag would be enough.
