### ISSUE TITLE
Startup errors crashing in log statement

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#308]
We have a recurrent error in our Scout stack, which seems to stem from me adding Chanjo2.

Every weekend Chanjo2 seems to end up in an infinite startup loop. Not sure exactly what is happening, but guessing we do backups of mongodb for instance during the weekend.

After doing a full Scout stack restart everything runs as normal again. (This is confusing to me. Unsure what is different here).

Looking at the logs, there is a stack trace originating from this log statement:

```
ESC[36mchanjo2               |ESC[0m Traceback (most recent call last):
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
ESC[36mchanjo2               |ESC[0m     msg = self.format(record)
ESC[36mchanjo2               |ESC[0m           ^^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
ESC[36mchanjo2               |ESC[0m     return fmt.format(record)
ESC[36mchanjo2               |ESC[0m            ^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
ESC[36mchanjo2               |ESC[0m     msg = self.format(record)
ESC[36mchanjo2               |ESC[0m           ^^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 690, in format
ESC[36mchanjo2               |ESC[0m     s = self.formatMessage(record)
ESC[36mchanjo2               |ESC[0m         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
ESC[36mchanjo2               |ESC[0m     return fmt.format(record)
ESC[36mchanjo2               |ESC[0m            ^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/venv/lib/python3.11/site-packages/uvicorn/logging.py", line 104, in formatMessage
ESC[36mchanjo2               |ESC[0m     (
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/logging/__init__.py", line 690, in format
ESC[36mchanjo2               |ESC[0m     s = self.formatMessage(record)
ESC[36mchanjo2               |ESC[0m         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ESC[36mchanjo2               |ESC[0m   File "/venv/lib/python3.11/site-packages/uvicorn/logging.py", line 104, in formatMessage
ESC[36mchanjo2               |ESC[0m     (
ESC[36mchanjo2               |ESC[0m ValueError: not enough values to unpack (expected 5, got 0)
```

```
ESC[36mchanjo2               |ESC[0m   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
ESC[36mchanjo2               |ESC[0m     await self.app(scope, receive, send)
ESC[36mchanjo2               |ESC[0m   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 707, in __call__
ESC[36mchanjo2               |ESC[0m     await self.lifespan(scope, receive, send)
ESC[36mchanjo2               |ESC[0m   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
ESC[36mchanjo2               |ESC[0m     async with self.lifespan_context(app) as maybe_state:
ESC[36mchanjo2               |ESC[0m   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
ESC[36mchanjo2               |ESC[0m     return await anext(self.gen)
ESC[36mchanjo2               |ESC[0m   File "/home/worker/app/src/chanjo2/main.py", line 33, in lifespan
ESC[36mchanjo2               |ESC[0m     LOG.info("Starting up...")
ESC[36mchanjo2               |ESC[0m Message: 'Starting up...'
ESC[36mchanjo2               |ESC[0m Arguments: ()
```

It looks like the logger expects additional arguments, but does not obtain any.

Checking the code it looks like `uvicorn` is configured as a logger. I also configured to use it as a "runner" to get the sub-route working.

Googling around I see other encountering similar issues:

- https://github.com/tiangolo/fastapi/issues/5542
- https://github.com/encode/uvicorn/discussions/1450

Looks like this possibly could be resolved either by configuration, or by swapping the logger.

I am on the edge of my knowledge here though! Do you see the issue more clearly?

**Comment by northwestwitch** [comment]
Hi @Jakob37, we never saw this error but I guess it's because we don't use uvicorn as a runner, like you guys do. We don't have to have uvicorn handling the logging. I'll open a PR with a change

**Comment by Jakob37** [comment]
> Hi @Jakob37, we never saw this error but I guess it's because we don't use uvicorn as a runner, like you guys do. We don't have to have uvicorn handling the logging. I'll open a PR with a change

OK thanks!

**Comment by northwestwitch** [comment]
What's the code you use to start the server? Are your providing a log config file?

**Comment by northwestwitch** [comment]
Also, are you passing a log config file when you start the app?

**Comment by Jakob37** [comment]
> What's the code you use to start the server? Are you logging to file?

Here is the command we use to start Chanjo2:

```
command: ["uvicorn", "chanjo2.main:app", "--host=0.0.0.0", "--port=8000", "--workers=2", "--log-level=info", "--root-path=/chanjo2"]
```

> Also, are you passing a log config file when you start the app?

Hmm, looks like not. Sounds like something worth trying out.

**Comment by northwestwitch** [comment]
> Hmm, looks like not, not intentionally at least.

We don't have a log config file either. It's weird, because if the app works fine with the command you mentioned I don't understand why you get that error over weekends. I'm not sure how to fix the logging since I don't understand what's really going on. 
Looks like the app is restarted in the wrong way by some process because you get a call to [lifespan](https://github.com/Clinical-Genomics/chanjo2/blob/7e845ac45805dba8332dee341a8c37677b4f3387/src/chanjo2/main.py#L32). Chanjo2 is working with a MySQL database so it shouldn't be affected by the MongoDB backups. Please try to investigate a bit more what can be trying to restart chanjo2 on your side.

**Comment by Jakob37** [comment]
> > Hmm, looks like not, not intentionally at least.
> 
> We don't have a log config file either. It's weird, because if the app works fine with the command you mentioned I don't understand why you get that error over weekends. I'm not sure how to fix the logging since I don't understand what's really going on. Looks like the app is restarted in the wrong way by some process because you get a call to [lifespan](https://github.com/Clinical-Genomics/chanjo2/blob/7e845ac45805dba8332dee341a8c37677b4f3387/src/chanjo2/main.py#L32). Chanjo2 is working with a MySQL database so it shouldn't be affected by the MongoDB backups. Please try to investigate a bit more what can be trying to restart chanjo2 on your side.

OK, I'll investigate a bit more!

**Comment by northwestwitch** [comment]
> OK, I'll investigate a bit more!

One thing that comes to my mind is that perhaps database and logging initiation should be presen on a app startup function and not on a lifespan one (which gets executed also when the app stops or reboots)- I'll fix accordingly, and perhaps this will solve your issue

**Comment by Jakob37** [comment]
> Chanjo2 is working with a MySQL database so it shouldn't be affected by the MongoDB backups.

Hmm, aha. I had misunderstood here. I thought the SQL database was used only for intervals, but I see now that it also stores the cases and samples.

I currently have the mongodb container as a dependency for Chanjo2. Maybe that is part of what is happening here. I'll remove it.

**Comment by northwestwitch** [comment]
You can store cases and samples in MySQL if you want, but it's optional really. Yes, MongoDB is not used at all here so yes, it should be removed

**Comment by Jakob37** [comment]
> You can store cases and samples in MySQL if you want, but it's optional really. Yes, MongoDB is not used at all here so yes, it should be removed

OK I understand! OK I'll remove the dependency.

**Comment by Jakob37** [comment]
I think this will fix it. Closing for now. Reopening if it comes back.

**Comment by Jakob37** [comment]
Looks like it came back, without the mongodb dependency and with the updated version running the log statement from within the lifetime method.

I guess there are two parts here. 

(1) Why is Chanjo2 restarting (must be something in our setup)
(2) Why does it crash on logging

I'll see if I can configure uvicorn somehow such that it doesn't crash on logging.

**Comment by Jakob37** [comment]
Question @northwestwitch , in the `logger.py`, specifically this part:

```
if LOG.handlers:
    LOG.handlers[0].setFormatter(console_formatter)
else:
    logging.basicConfig()
```

If the else-statement is hit for some reason, `logging.basicConfig()` is called. This does not seem to update the `LOG` instance, which later is used. Could this cause issues?

Anyway, I'll try to see if I can reproduce the error on my laptop. I think with a quicker cycle, I should be able to pinpoint the error.

**Comment by northwestwitch** [comment]
Ok! I'll look into it

**Comment by Jakob37** [comment]
It looks like this update fixed the error - the logs look clean now.

We still have the issue with Chanjo2 not running after every weekend though 🤔 But seems more and more likely that this is related to our setup rather than Chanjo2.

Anyway, I think this issue is resolved. I'll continue digging. If it still seems related to Chanjo2 internals, I'll be back with a separate issue.

**Comment by northwestwitch** [comment]
> Anyway, I think this issue is resolved. I'll continue digging. If it still seems related to Chanjo2 internals, I'll be back with a separate issue.

Please do that! Thanks for reporting and sorry if we couldn't pinpoint the issue better

**Comment by Jakob37** [comment]
We fixed the restart issue. It was a simple one. I had missed adding an auto-restart attribute to the chanjo2-process in our yaml, which the other processes had.

I guess the processes were stopped during backing up in the weekends, and then the Chanjo2 one failed to start again.

Seems the log error was unrelated. Nice that it was fixed anyway!

**Comment by northwestwitch** [comment]
> We fixed the restart issue. It was a simple one. I had missed adding an auto-restart attribute to the chanjo2-process in our yaml, which the other processes had.
> 
> I guess the processes were stopped during backing up in the weekends, and then the Chanjo2 one failed to start again.
> 
> Seems the log error was unrelated. Nice that it was fixed anyway!

Ah, it makes sense. Good that you found out what it was in the end!
