### ISSUE TITLE
Improve performance of get_coverage_completeness.py

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#316]
As discussed in [#299](https://github.com/Clinical-Genomics/chanjo2/issues/299), the current performance bottleneck seems to be the get_coverage_completeness.py function. If we could resolve this, it would be great for the Chanjo2 usability.

It is both something that would make the switch to Chanjo2 more smooth and an interesting problem.

Here is a snakeviz profiling from running ~70 intervals with three thresholds (10, 20, 30). It seems to me most time is spend parsing output from the d4tools view output

![image](https://github.com/Clinical-Genomics/chanjo2/assets/28093618/a9f4df9b-52b5-4b1c-8068-347fa0ff913d)

I also tried using the d4tools stat -stat hist output and checking the fraction at or above specific thresholds. This seemed to give correct values, but processing time is similar - again time spent at parsing output from the command.

```
        command = f"bash -c \"{D4_TOOLS} stat --stat hist --region <(echo '{coords[0]} {coords[1]} {coords[2]}' | tr ' ' '\t') {d4_file_path}\""
        hist_results: List[str] = subprocess.check_output(
            "".join(command),
            shell=True,
            text=True,
        ).splitlines()

        hist_results_num_bin = [[int(pair.split()[0]), int(pair.split()[1])] for pair in hist_results[1:-1]]
        total = sum([pair[1] for pair in hist_results_num_bin])
        for threshold in thresholds:
            threshold_sum = sum([pair[1] for pair in hist_results_num_bin if pair[0] >= threshold])
            print(f"sum {total} threshold {threshold_sum} above {threshold_sum / total}")
```
It spontaneously looks to me that the ideal solution would be to get in a new stat function into d4tools which runs similarly to the mean calculations - giving an output as such:

```
$ d4tools stat --stat cov_at_thres --thresholds 10 20 30
chr    start    end     perc_thres1     perc_thres2     perc_thres3
```

This should be much quicker, but unsure how smooth it would be technically and socially to squeeze it into d4tools 🤔 Maybe worth raising an issue, if we think this is the way to go.

Otherwise it seems we would like somehow directly read from the d4 file using code in the d4tool. Probably feasible as well. Not sure how to package this in a non-messy way though.

Might be a good starting point to just fork d4tools and see if we could get it to do what we want here and see the performance. If it works, then think about how to package this.

Do you have thoughts on this?

Needless to say, this would be useful for us and I am happy to help 🙂

**Comment by northwestwitch** [comment]
> I also tried using the `d4tools stat -stat hist` output and checking the fraction at or above specific thresholds. This seemed to give correct values, but processing time is similar - again time spent at parsing output from the command.

Shame, but yes, makes sense.


> It spontaneously looks to me that the ideal solution would be to get in a new stat function into `d4tools` which runs similarly to the mean calculations - giving an output as such:

```
> $ d4tools stat --stat cov_at_thres --thresholds 10 20 30
chr    start    end     perc_thres1     perc_thres2     perc_thres3
...
```

>This should be much quicker, but unsure how smooth it would be technically and socially to squeeze it into d4tools 🤔 Maybe worth raising an issue, if we think this is the way to go.

That's exactly what I was thinking but I've never opened an issue on d4tools with the request because I figured they would never work on it if they still had those important bugs unfixed. I guess one could try now that it seems things are moving on their side. Let's open an issue and see what they say, perhaps?

> Otherwise it seems we would like somehow directly read from the d4 file using code in the d4tool. Probably feasible as well. Not sure how to package this in a non-messy way though.

> Might be a good starting point to just fork d4tools and see if we could get it to do what we want here and see the performance. If it works, then think about how to package this.

Or we can create a PR in d4tools so they include it in the official repo!

> Needless to say, this would be useful for us and I am happy to help 🙂 

Nice, thanks! 🚀

**Comment by northwestwitch** [comment]
Sorry I messed up with the comments. Now it should be back to how it was :)

**Comment by Jakob37** [comment]
> Or we can create a PR in d4tools so they include it in the official repo!

Yes, I agree, that would be the ideal!

I think most of the building blocks to get this functionality in place should be in d4tools already. So shouldn't be super-difficult ... But we'll see.

**Comment by Jakob37** [comment]
I opened an issue over at the d4tools: https://github.com/38/d4-format/issues/81

**Comment by northwestwitch** [comment]
> I opened an issue over at the d4tools: [38/d4-format#81](https://github.com/38/d4-format/issues/81)

Nice! And I saw that somebody offered to work on it already!! 🥳

**Comment by northwestwitch** [comment]
We can fix chanjo2 once d4tools has this [this](https://github.com/38/d4-format/pull/83) in place

**Comment by Jakob37** [comment]
> We can fix chanjo2 once d4tools has this [this](https://github.com/38/d4-format/pull/83) in place

Yes, great. I'll gently ping and see if we can get things moving.
