### ISSUE TITLE
Clarify "Average coverage"

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#325]
I have been looking at confirming that the Chanjo2 numbers are correct post-d4tools update. Conclusion is that it looks fine, but there are some points to consider.

I got slightly different numbers at first between what I saw for a small panel in Chanjo2 and by manually summing the counts in the target regions using `d4tools show`.

I eventually realized/re-remembered that the "Average coverage" is the mean of the individual coverage values from each gene. I was calculating the average coverage across the pooled genes.

I suspect this is how the "Completeness" values are calculated, i.e. for pooled genes rather than the mean of individual gene completenesses.

Not sure which is better, but I would suggest writing this out somewhere on the page, either in the docs part at the bottom, and/or perhaps better, as a tooltip when hovering the table header.

**Comment by northwestwitch** [comment]
Tooltip is a good idea. I'll work on it!

**Comment by northwestwitch** [comment]
Coverage report contains an explanation towards the end of the document. Perhaps I could expand there and it would be more clear
