### ISSUE TITLE
MANE transcripts

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#354]
I put the latest Chanjo2 in the hands of our geneticists and asked them what they would need to put this into clinical routine. It seems close to meet their needs, but they had a bunch of questions on updates to make it fully solve their situation. Let's see what you think - if reasonable or not.

**Describe the solution you'd like**

The geneticists in Lund primarily work with MANE transcripts. Other transcripts are not of interest. (Is it the same in Stockholm?)

On the overview page, a column showing MANE completeness could be shown instead or in addition to the gene column. Would this be possible?

![incomplete_genes_overview](https://github.com/user-attachments/assets/6eec9c2a-1caf-41d3-af70-b2496d3fe7f7)

Other ideas are welcome as well. Right now, it takes too long time to load the gene specific page (~1 min each), so it would not be feasible for them to click through a bunch of those to check the coverage for their transcript of interest.

**Comment by northwestwitch** [comment]
> The geneticists in Lund primarily work with MANE transcripts. Other transcripts are not of interest. (Is it the same in Stockholm?)
> 
> On the overview page, a column showing MANE completeness could be shown instead or in addition to the gene column. Would this be possible?

Yes, it's a good suggestion, and I believe it won't be complicated to implement. We are already saving the MANE info in the sql database of chanjo2.  Our WGS and WES data is still in build 37, so unfortunately MANE tags aren't available to our clinicians (yet). But we are slowly moving to build 38, hopefully next year! 🤞🏻

**Comment by northwestwitch** [comment]
What about a dedicated report containing only stats from MANE transcripts? Like the oveview one, but containing all MANE transcripts for all genes of a panel, with coverage and coverage completeness at the given thresholds?

**Comment by Jakob37** [comment]
> What about a dedicated report containing only stats from MANE transcripts? Like the overview one, but containing all MANE transcripts for all genes of a panel, with coverage and coverage completeness at the given thresholds?

Yes, a dedicated MANE-overview-report sounds like a great idea! To my understanding, this (in combination with access to exon specific coverage) would be exactly what the geneticists here would need.

**Comment by northwestwitch** [comment]
Ok, I can draft something and open a PR today or early next week

**Comment by Jakob37** [comment]
> Ok, I can draft something and open a PR today or early next week

Sounds great 😄
