### ISSUE TITLE
Gene page performance

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#357]
Right now, the gene page takes a minute or so to load. This becomes unfeasible when working through a list of many partially covered genes.

Testing it out, it took ~3 minutes for one gene to load:

![gene_overview_loading_time](https://github.com/user-attachments/assets/a592e814-33ea-4a69-bca4-32ff1e0ba4e1)

Btw I am happy to help out with hands-on contribution, both through code and testing. Just let me know if needed / wanted, and we can coordinate :)

**Comment by northwestwitch** [comment]
I agree that the page needs refactoring to speed up the report.  I am currently doing some cleaning and refactoring in #358 so the code might change, but afterwards yes, thank you! 🙏🏻

**Comment by Jakob37** [comment]
> I agree that the page needs refactoring to speed up the report. I am currently doing some cleaning and refactoring in https://github.com/Clinical-Genomics/chanjo2/pull/358 so the code might change, but afterwards yes, thank you! 🙏🏻

OK, nice! I'll give this one a stab next week then.

**Comment by Jakob37** [comment]
> > OK, nice! I'll give this one a stab next week then.
> 
> I've already started working on this one, shouldn't take me so long I think

OK, even better 😄
