### ISSUE TITLE
Link directly to overview report on case page

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#359]
The geneticists stuggled to find the panel-wide coverage summary (that can be reached through the panel).

They also reflected that it was hard to navigate back, as the bread-crumb for the panel does not include the case.

**Describe the solution you'd like**

Would it be possible to add a link to the coverage summary directly on the case page, i.e. under "Reports", or if not suitable, somewhere else?

![top_left](https://github.com/user-attachments/assets/a3aa5b76-e7b3-407e-ac46-4fb5898b421e)

(Or if you have other suggestions making it more accessible!)

**Comment by northwestwitch** [comment]
In case you didn't find this issue any more, it was me that moved it here ---> https://github.com/Clinical-Genomics/scout/issues/4893 😆

**Comment by Jakob37** [comment]
> In case you didn't find this issue any more, it was me that moved it here ---> [Clinical-Genomics/scout#4893](https://github.com/Clinical-Genomics/scout/issues/4893) 😆

🤣 

OK, I had the feeling that I already had written it.

Closing this one 😄
