### ISSUE TITLE
Support for custom panel probes

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#375]
We had a discussion today about using Chanjo2's coverage reports in our somatic workflows.

A key issue in the somatics is that they typically sequence panels with probes deciding what locations in the genes will be sequenced. (Typically this seems to correspond well with exons).

This means that the overall sequence coverage for genes will not be informative - introns for instance are typically not expected to be covered. Which would result in low coverage values for genes.

The end goal would be to quickly pick up for instance if an exon is lowly covered. If the coverage would be for probe regions only, they would see the overall drop and then zoom in on the exon level coverage.

**Describe the solution you'd like**

One idea would be to allow providing a bed file with the probe regions, i.e. the expected covered regions. Then each gene could use this to see what parts of it are expected to be covered, and calculate coverage for these.

I.e. if asking for the SMN1 gene for instance, it would check the bed file for what ranges are overlapping with it, and feed these ranges to d4tools. The result would be "coverage for probe regions within SMN1".

What do you think about this? Maybe this is a question that might also come up among Stockholm geneticists using panels?

**Additional **context****

This is relevant also in our constitutional pipeline where we run panels as well as wgs.

**Comment by Jakob37** [comment]
> Are these cases in scout or are they disconnected? There is already an endpoint allowing you to compute statisctics if you pass the path to a d4 file and a bed file with the intervals, but it doesn't create a report, just a json-formatted result -->
> 
> https://github.com/Clinical-Genomics/chanjo2/blob/4e292679f56e50d03d3bb83390d8eeb0ca485eef/src/chanjo2/endpoints/coverage.py#L87

The somatic cases are not in Scout, we are using a local solution for those. (For the constitutional though the panel cases are in Scout).

Yes, I mentioned that end point as a possibility during the meeting. That is definitely one possibility, maybe that would be the best way to go. The downside would be that we lose the nice reports of Chanjo2.

But if I can circle back to the question. Have you guys considered running Chanjo2 for panel cases or perhaps for exome sequencing? Where coverage over a genes exons (or probe ranges) is what is interesting rather than the full genes.

**Comment by northwestwitch** [comment]
> The somatic cases are not in Scout, we are using a local solution for those. (For the constitutional though the panel cases are in Scout).
> 
> Yes, I mentioned that end point as a possibility during the meeting. That is definitely one possibility, maybe that would be the best way to go. The downside would be that we lose the nice reports of Chanjo2.

I see. One could also create a nice report from an endpoint that accepts bed files intead of genes. 

> But if I can circle back to the question. Have you guys considered running Chanjo2 for panel cases or perhaps for exome sequencing? Where coverage over a genes exons (or probe ranges) is what is interesting rather than the full genes.

Of course, but scout cases analysed with WES will already have all chanjo2 reports based on exons. It works like this:
if you have at least one individual of the case analysed with WES, then the case reports will be based on exons intervals. Check the corresponding code here -> https://github.com/Clinical-Genomics/scout/blob/50051995952c1c41d64fcd6e7ce57e936c3aa2e4/scout/server/blueprints/cases/templates/cases/chanjo2_form.html#L22

**Comment by Jakob37** [comment]
> > The somatic cases are not in Scout, we are using a local solution for those. (For the constitutional though the panel cases are in Scout).
> > Yes, I mentioned that end point as a possibility during the meeting. That is definitely one possibility, maybe that would be the best way to go. The downside would be that we lose the nice reports of Chanjo2.
> 
> I see. One could also create a nice report from an endpoint that accepts bed files intead of genes.
> > But if I can circle back to the question. Have you guys considered running Chanjo2 for panel cases or perhaps for exome sequencing? Where coverage over a genes exons (or probe ranges) is what is interesting rather than the full genes.
> 
> Of course, but scout cases analysed with WES will already have all chanjo2 reports based on exons. It works like this: if you have at least one individual of the case analysed with WES, then the case reports will be based on exons intervals. Check the corresponding code here -> https://github.com/Clinical-Genomics/scout/blob/50051995952c1c41d64fcd6e7ce57e936c3aa2e4/scout/server/blueprints/cases/templates/cases/chanjo2_form.html#L22
> 
> specifically lines 22 to 30

Aha, I see! Sounds like we should investigate the exon report closer. I'll give it a try. Maybe that would work for our panel cases as well. We should ponder this a bit more anyway.

I'll close the issue. Thanks 😊

**Comment by Jakob37** [comment]
> It won't work on the cases that are not in scout though. Just re-open the issue if some fix is needed! 👍🏻

Will do, thanks!
