### ISSUE TITLE
Create endpoint for fetching coverage data from a genomic range 

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/chanjo2#5]
- [ ] establish what input arguments are to be provided to the API and how those should be formatted (should be easy to parse/embed Schug json response)
- [ ] establish how response model should be formatted (what is the response expected by scout/chanjoreport?)

**Comment by northwestwitch** [comment]
This is done:

- Endpoint to calculate range over one interval (can eventually be an entire chromosome)

<img width="666" alt="image" src="https://github.com/Clinical-Genomics/chanjo2/assets/28093618/9bb8886d-6cab-44fe-aac9-e2b6e54a8430">
