### ISSUE TITLE
Create endpoint for fetching coverage statistics from a bed file

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/chanjo2#6]
- [ ] Define input and output models of endpoint
- [ ] Evaluate response time of the endpoint given different approaches

**Comment by northwestwitch** [comment]
This is done:

- Endpoint that accepts the path to a d4 file (local or remote) and a bed file with genomic ranges:

<img width="670" alt="image" src="https://github.com/Clinical-Genomics/chanjo2/assets/28093618/ec38adce-2d04-438c-be80-22311f0a33c5">
